var theArray=new Array();
theArray[0]="你的笑或是一方良药！";
theArray[1]="如若不是为了一个人，谁肯枯守一座城。";
theArray[2]="枕头上还沾了些许为你流的泪...";
theArray[3]="你每一丝微笑都那么赏心悦目。";
theArray[4]="或许,命运织线已将你我交错相连。";
theArray[5]="多希望你无人问津，全世界喜欢你的只有我一个。";
theArray[6]="你是个大坑,使我越陷越深...";
theArray[7]="我不会再错过你了,我不能再错过你了。";
theArray[8]="即使这样，我也觉得能遇上你真的太好了。";
theArray[9]="你是我的太阳！";
theArray[10]="若结局非你所愿，就在尘埃落定前奋力一搏。";
theArray[11]="唯有有你,一直陪在我身边..";
theArray[12]="假如我们相遇，肯定一眼就能认出彼此。";
theArray[13]="我已记不得你的名字，却还记得喜欢你。";
theArray[14]="时间带着明显的恶意，缓缓在我的身上流逝。";
theArray[15]="织女和牛郎无论下多少雨都不会彼此忘记吧。";
theArray[16]="不是在最好的时光遇见你，而是遇到你之后才是最好的时光。";
theArray[17]="你即是我行走的方向。";
theArray[18]="如果说我遇到你，变得更好了的话，那么我想，把这样的自己保留下来，努力地迎接接下来的每一天。";
theArray[19]="我知道,爱你是要付出代价的,但我不惜遍体鳞伤..";
theArray[20]="时间流逝,唯独忘不了你...";
theArray[21]="你有何本事留着比你优秀的人？";
theArray[22]="Try to be the best！";
theArray[23]="时间磨尽了山盟海誓,你我倘若路人。";
theArray[24]="我接受你的挑战！";
theArray[25]="Come on！";
theArray[26]="真可笑...还没忘掉,就已深深地爱上你了。";
theArray[27]="我曾狂言超越,结局却是一次又一次惨败..";
theArray[28]="我怕在我离开时,都忘不了与你再一次对视..";
theArray[29]="可能我一直错了,一直把你当成社稷。";
theArray[30]="明显,我不是你的对手..但我相信,我才会笑到最后！";
theArray[31]="认真拿好这次属于你的一血吧！";
theArray[32]="你尽管拿你的MVP,我拿Victory就行了！";
theArray[33]="其实,你并没有退步,只是跟丢了。";
theArray[34]="时代在召唤..";
theArray[35]="一步之遥,志在必得！";
theArray[36]="万般带不走,只有孽随身。";
theArray[37]="生死有命,富贵在天！";
theArray[38]="不会止步,只能前行。";
theArray[39]="你知不知道,我想你了。";
theArray[40]="为何还抓住那段回忆久久不放...";
theArray[41]="宁愿死得干干净净,也不要苟延残喘。";
theArray[42]="要是活的不自由,人生还有什么意思呢？";
theArray[43]="风住尘香花已尽,日晚倦梳头。";
theArray[44]="丧失性情的我,竟能对你如此痴迷。";
theArray[45]="趁早放弃,不如背水一战。";
theArray[46]="I honestly love you.";
theArray[47]="多希望,能和你搭上第一句话。";
theArray[48]="我很害怕再也见不到你...";
theArray[49]="不能挽回,那就放下吧！";
theArray[50]="世上会因我翻天覆地。";
theArray[51]="倘若连承担都不行,谈何赤裸裸的爱。";

function ranFun()
{
 return parseInt(Math.random()*51);
}
document.write(theArray[ranFun()]);