<?php
$id=rand(1,23);
$image[1]='https://file.bakadax.top/?/backgroud/pe/1.jpg';
$image[2]='https://file.bakadax.top/?/backgroud/pe/2.jpg';
$image[3]='https://file.bakadax.top/?/backgroud/pe/3.jpg';
$image[4]='https://file.bakadax.top/?/backgroud/pe/4.jpg';
$image[5]='https://file.bakadax.top/?/backgroud/pe/5.jpg';
$image[6]='https://file.bakadax.top/?/backgroud/pe/6.jpg';
$image[7]='https://file.bakadax.top/?/backgroud/pe/7.jpg';
$image[8]='https://file.bakadax.top/?/backgroud/pe/8.jpg';
$image[9]='https://file.bakadax.top/?/backgroud/pe/9.jpg';
$image[10]='https://file.bakadax.top/?/backgroud/pe/10.jpg';
$image[11]='https://file.bakadax.top/?/backgroud/pe/11.jpg';
$image[12]='https://file.bakadax.top/?/backgroud/pe/12.jpg';
$image[13]='https://file.bakadax.top/?/backgroud/pe/13.jpg';
$image[14]='https://file.bakadax.top/?/backgroud/pe/14.jpg';
$image[15]='https://file.bakadax.top/?/backgroud/pe/15.jpg';
$image[16]='https://file.bakadax.top/?/backgroud/pe/16.jpg';
$image[17]='https://file.bakadax.top/?/backgroud/pe/17.jpg';
$image[18]='https://file.bakadax.top/?/backgroud/pe/18.jpg';
$image[19]='https://file.bakadax.top/?/backgroud/pe/19.jpg';
$image[20]='https://file.bakadax.top/?/backgroud/pe/20.jpg';
$image[21]='https://file.bakadax.top/?/backgroud/pe/21.jpg';
$image[22]='https://file.bakadax.top/?/backgroud/pe/22.jpg';
$image[23]='https://file.bakadax.top/?/backgroud/pe/23.jpg';
header("location:$image[$id]");
?> 