<?php 
if(!defined('EMLOG_ROOT')) {exit('error!');} 
?>
<a href="javascript:grin('[F1]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/1.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F2]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/2.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F3]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/3.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F4]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/4.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F5]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/5.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F6]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/6.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F7]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/7.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F8]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/8.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F9]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/9.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F10]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/10.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F11]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/11.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F12]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/12.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F13]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/13.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F14]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/14.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F15]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/15.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F16]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/16.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F17]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/17.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F18]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/18.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F19]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/19.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F20]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/20.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F21]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/21.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F22]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/22.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F23]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/23.gif" height="20" width="20"/></a>
<a href="javascript:grin('[F24]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/24.gif" height="20" width="20"/></a>
<a href="javascript:grin('[F25]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/25.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F26]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/26.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F27]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/27.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F28]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/28.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F29]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/29.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F30]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/30.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F31]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/31.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F32]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/32.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F33]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/33.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F34]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/34.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F35]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/35.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F36]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/36.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F37]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/37.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F38]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/38.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F39]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/39.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F40]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/40.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F41]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/41.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F42]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/42.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F43]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/43.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F44]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/44.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F45]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/45.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F46]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/46.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F47]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/47.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F49]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/48.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F49]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/49.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F50]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/50.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F51]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/51.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F52]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/52.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F53]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/53.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F54]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/54.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F55]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/55.gif" height="20" width="20"/></a>
<a href="javascript:grin('[F56]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/56.gif" height="20" width="20"/></a>
<a href="javascript:grin('[F57]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/57.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F58]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/58.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F59]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/59.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F60]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/60.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F61]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/61.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F62]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/62.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F63]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/63.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F64]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/64.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F65]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/65.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F66]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/66.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F67]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/67.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F68]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/68.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F69]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/69.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F70]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/70.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F71]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/71.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F72]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/72.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F73]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/73.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F74]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/74.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F75]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/75.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F76]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/76.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F77]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/77.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F78]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/78.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F79]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/79.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F80]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/80.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F81]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/81.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F82]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/82.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F83]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/83.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F84]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/84.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F85]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/85.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F86]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/86.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F87]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/87.gif" height="20" width="20"/></a>
<a href="javascript:grin('[F88]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/88.gif" height="20" width="20"/></a>
<a href="javascript:grin('[F89]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/89.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F90]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/90.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F91]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/91.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F92]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/92.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F93]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/93.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F94]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/94.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F95]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/95.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F96]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/96.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F97]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/97.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F98]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/98.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F99]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/99.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F100]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/100.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F101]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/101.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F102]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/102.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F103]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/103.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F104]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/104.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F105]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/105.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F106]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/106.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F107]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/107.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F108]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/108.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F109]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/109.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F110]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/110.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F111]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/111.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F112]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/112.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F113]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/113.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F114]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/114.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F115]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/115.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F116]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/116.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F117]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/117.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F118]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/118.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F119]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/119.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F120]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/120.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F121]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/121.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F122]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/122.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F123]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/123.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F124]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/124.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F125]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/125.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F126]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/126.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F127]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/127.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F128]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/128.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F129]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/129.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F130]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/130.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F131]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/131.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F132]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/132.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F133]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/133.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F134]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/134.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F135]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/135.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F136]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/136.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F137]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/137.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F138]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/138.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F139]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/139.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F140]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/140.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F141]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/141.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F142]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/142.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F143]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/143.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F144]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/144.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F145]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/145.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F146]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/146.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F147]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/147.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F148]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/148.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F149]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/149.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F150]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/150.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F151]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/151.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F152]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/152.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F153]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/153.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F154]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/154.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F155]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/155.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F156]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/156.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F157]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/157.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F158]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/158.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F159]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/159.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F160]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/160.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F161]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/161.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F162]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/162.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F163]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/163.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F164]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/164.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F165]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/165.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F166]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/166.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F167]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/167.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F168]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/168.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F169]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/169.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F170]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/170.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F171]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/171.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F172]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/172.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F173]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/173.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F174]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/174.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F175]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/175.gif" height="30" width="30"/></a>
<a href="javascript:grin('[F176]')"><img src="<?php echo TEMPLATE_URL; ?>images/face/176.gif" height="30" width="30"/></a>